name: pushMigrations

on:
  push:
    branches:
      - main
    paths:
        pg-migrations/**


jobs:
    build-and-push-migrations:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}
            
            - name: Build Docker image
              uses: docker/build-push-action@v2
              with:
                    context: .
                    file: ./pg-migrations/Dockerfile
                    push: true
                    tags: 09078601/migrations:v1.0.2
                    no-cache: true